#!/usr/bin/env bash
# ARCHIVED, 2026-09-10. NOT WIRED INTO ANYTHING.
#
# This script was written for a LinkedIn announce-post integration that was
# never built, because the research it accompanied concluded there is no API
# path to the profile fields this repository generates. It is preserved because
# it works, it is tested, and rewriting it would cost more than reading it.
#
# What it is for, what it encodes, and what to do if it is ever needed:
#   llm-wiki/wiki/sources/archived-linkedin-secrets-tool.md
#
# Do not edit this file. It is immutable archive material. If it is revived,
# copy it out and change the copy.
# Store the LinkedIn integration's credentials in the login keyring, and make
# the subset that cannot be regenerated safe to back up off this machine.
#
# Two rules shape everything here:
#
#   1. A secret never appears in a command-line argument. Arguments are visible
#      in `ps`, in /proc, and in shell history, and on a machine where an AI
#      agent reads the terminal they are visible there too. Every value is read
#      from stdin or from a silent prompt.
#
#   2. `secret-tool search` PRINTS SECRET VALUES in plaintext. That makes the
#      obvious way to list what you have stored a way to splash every
#      credential across the terminal and its scrollback. `list` below filters
#      those lines out and shows only names and metadata.
#
# Secrets are tagged `backup=required` or `backup=derived`:
#
#   required  Losing it costs a trip through a web console to reissue, or is
#             unrecoverable. These are what `export` bundles for cloud storage.
#   derived   Regenerable at any time from the required ones. Never exported —
#             backing up a short-lived token achieves nothing and widens the
#             blast radius of the backup.
#
# The export bundle is symmetrically encrypted with GnuPG before it ever exists
# as a file, so the plaintext is never written to disk and the file is safe to
# put in cloud storage. Cloud storage is assumed hostile: it is a place that
# holds ciphertext, not a place you trust.
#
# This script never makes a network request. Its sibling `linkedin_sync.py`
# never touches secrets. Keeping the two apart means neither can leak into the
# other, and each can be read in one sitting.
set -Eeuo pipefail

SERVICE="linkedin-resume"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# Everything this script writes is either a secret or a bundle of them.
umask 077

command -v secret-tool >/dev/null 2>&1 ||
  die "secret-tool not found. Install it:  sudo pacman -S libsecret"

# Which credentials this integration uses, and whether losing one is recoverable
# without a trip to the LinkedIn developer console.
declare -A ACCOUNTS=(
  [client-id]="required:LinkedIn app Client ID"
  [client-secret]="required:LinkedIn app Client Secret — reissuable, but it rotates every app that uses it"
  [refresh-token]="required:OAuth refresh token, ~1 year, costs a browser round trip to replace"
  [access-token]="derived:OAuth access token, ~60 days, minted from the refresh token"
  [person-urn]="derived:Your member URN, re-fetchable from the userinfo endpoint"
)

usage() {
  cat <<'EOF'
Usage: secrets.sh <command> [account]

  set <account>       Store a value, read from a silent prompt (or stdin if piped)
  get <account>       Print one value to stdout — pipe it, do not let it sit on screen
  list                Show what is stored. Never prints secret values
  rm <account>        Remove one value
  accounts            Show the account names this integration uses

  export <file.gpg>   Encrypt the backup=required values into a bundle for cloud storage
  import <file.gpg>   Restore a bundle into the keyring on a new machine

Accounts:
EOF
  local name spec
  for name in $(printf '%s\n' "${!ACCOUNTS[@]}" | sort); do
    spec="${ACCOUNTS[$name]}"
    printf '  %-16s %-9s %s\n' "${name}" "[${spec%%:*}]" "${spec#*:}"
  done
}

check_account() {
  [ -n "${ACCOUNTS[$1]:-}" ] ||
    die "unknown account '$1'. Run 'secrets.sh accounts' for the list."
}

backup_class() { printf '%s' "${ACCOUNTS[$1]%%:*}"; }

cmd_set() {
  local account="$1" value
  check_account "${account}"

  if [ -t 0 ]; then
    # -s keeps it off the screen; it is read into a variable rather than passed
    # as an argument so it never reaches ps, /proc or shell history.
    printf 'Value for %s (input hidden): ' "${account}" >&2
    # `read` reports failure on EOF-without-newline even though it has read the
    # value; under `set -e` that would abort with nothing stored and no message.
    IFS= read -rs value || true
    printf '\n' >&2
  else
    IFS= read -r value || true
  fi
  [ -n "${value}" ] || die "empty value; nothing stored"

  printf '%s' "${value}" | secret-tool store \
    --label="LinkedIn resume publishing — ${account}" \
    service "${SERVICE}" \
    account "${account}" \
    backup "$(backup_class "${account}")"
  unset value
  printf 'stored %s (backup=%s)\n' "${account}" "$(backup_class "${account}")" >&2
}

cmd_get() {
  local account="$1"
  check_account "${account}"
  secret-tool lookup service "${SERVICE}" account "${account}" ||
    die "no value stored for '${account}'"
}

# `secret-tool search` prints `secret = <plaintext>` lines. Dropping them is the
# entire point of this wrapper: without it, "show me what I have stored" is a
# credential disclosure.
cmd_list() {
  local out
  # secret-tool writes its search results to STDERR, not stdout. Redirecting
  # stderr away — the reflex when a tool is noisy — silently discards the whole
  # listing and leaves you looking at an empty table.
  out="$(secret-tool search --all service "${SERVICE}" 2>&1 || true)"
  if [ -z "${out}" ]; then
    printf 'Nothing stored yet for service=%s\n' "${SERVICE}"
    return 0
  fi
  printf '%-16s %-9s %s\n' "ACCOUNT" "BACKUP" "MODIFIED"
  # A secret value may itself contain newlines, and its continuation lines sit
  # between `secret = ` and `created = `. Anything in that span is secret
  # material, so it is skipped wholesale rather than pattern-matched — a value
  # containing a line like "modified = ..." would otherwise print a fragment of
  # itself into this table.
  printf '%s\n' "${out}" \
    | awk '
        /^secret = /  { insecret = 1; next }
        /^created = / { insecret = 0 }
        insecret      { next }
        /^attribute\.account = / { acct = $3 }
        /^attribute\.backup = /  { bkp  = $3 }
        /^modified = /           { mod  = $3 }
        acct && bkp && mod { printf "%-16s %-9s %s\n", acct, bkp, mod; acct=bkp=mod="" }
      ' | sort
  printf '\n(values deliberately not shown; use `get` for one, into a pipe)\n'
}

cmd_rm() {
  local account="$1"
  check_account "${account}"
  secret-tool clear service "${SERVICE}" account "${account}"
  printf 'removed %s\n' "${account}" >&2
}

cmd_export() {
  local out="${1:-}"
  [ -n "${out}" ] || die "name the output file, e.g. linkedin-secrets.gpg"
  [ -e "${out}" ] && die "${out} already exists; refusing to overwrite a backup"
  command -v gpg >/dev/null 2>&1 || die "gpg not found. Install it: sudo pacman -S gnupg"

  local name value found=0 payload=""
  for name in $(printf '%s\n' "${!ACCOUNTS[@]}" | sort); do
    [ "$(backup_class "${name}")" = "required" ] || continue
    if value="$(secret-tool lookup service "${SERVICE}" account "${name}" 2>/dev/null)"; then
      payload+="${name}"$'\t'"${value}"$'\n'
      found=$((found + 1))
    else
      printf 'warning: %s is not stored; it will be missing from the bundle\n' "${name}" >&2
    fi
  done
  unset value
  [ "${found}" -gt 0 ] || die "nothing with backup=required is stored; nothing to export"

  # The plaintext goes straight down a pipe into gpg. It is never a temporary
  # file, so there is no window in which an unencrypted copy exists on disk and
  # nothing to shred afterwards.
  printf 'Choose a passphrase for the backup bundle.\n' >&2
  printf 'It protects every credential in it — use one you do not use elsewhere,\n' >&2
  printf 'and store it somewhere other than the cloud account holding the bundle.\n' >&2
  printf '%s' "${payload}" | gpg --symmetric --cipher-algo AES256 --output "${out}"
  unset payload

  printf '\nWrote %s (%s credential(s), AES-256).\n' "${out}" "${found}" >&2
  printf 'Safe to upload. Verify it before you rely on it:\n' >&2
  printf '  gpg --decrypt %s | cut -f1\n' "${out}" >&2
}

cmd_import() {
  local in="${1:-}"
  [ -n "${in}" ] || die "name the bundle file to import"
  [ -f "${in}" ] || die "no such file: ${in}"
  command -v gpg >/dev/null 2>&1 || die "gpg not found"

  local name value count=0
  while IFS=$'\t' read -r name value || [ -n "${name}" ]; do
    [ -n "${name}" ] || continue
    if [ -z "${ACCOUNTS[$name]:-}" ]; then
      printf 'warning: bundle contains unknown account %s; skipped\n' "${name}" >&2
      continue
    fi
    printf '%s' "${value}" | secret-tool store \
      --label="LinkedIn resume publishing — ${name}" \
      service "${SERVICE}" \
      account "${name}" \
      backup "$(backup_class "${name}")"
    printf 'restored %s\n' "${name}" >&2
    count=$((count + 1))
  done < <(gpg --quiet --decrypt "${in}"; printf '\n')
  unset value

  printf '\nRestored %s credential(s) into the keyring.\n' "${count}" >&2
  printf 'Derived values (access token, member URN) are not in the bundle by\n' >&2
  printf 'design; they are re-minted on the next run.\n' >&2
}

case "${1:-}" in
  set)      shift; [ $# -ge 1 ] || die "which account?"; cmd_set "$1" ;;
  get)      shift; [ $# -ge 1 ] || die "which account?"; cmd_get "$1" ;;
  rm)       shift; [ $# -ge 1 ] || die "which account?"; cmd_rm "$1" ;;
  list)     cmd_list ;;
  accounts) usage ;;
  export)   shift; cmd_export "${1:-}" ;;
  import)   shift; cmd_import "${1:-}" ;;
  ""|-h|--help|help) usage ;;
  *)        die "unknown command '$1'. Run 'secrets.sh --help'." ;;
esac
